---
top_mail: true

container_hostname: "mail{{ ip3 | default('') }}"
container_ipv4: "{{ container_ipv4_root }}.{{ param_ip4_mail }}"
container_ipv6: "{{ container_ipv6_root }}:{{ param_ip4_mail }}"
