---
all:
  children:
    baremetal:
      hosts:
        server:
        rescue:
    vps:
      hosts:
        bastion:
    containers:
      children:
        incus_proxy:
          hosts:
            proxy:
        incus_dokuwiki:
          hosts:
            dokuwiki:
        incus_dns:
          hosts:
            dns:
        incus_mail:
          hosts:
            mail:
        incus_sql:
          hosts:
            sql:
        incus_test:
          hosts:
            test:
