---
all:
  children:
    baremetal:
      children:
        server_host:
          hosts:
            server:
        server_rescue:
          hosts:
            rescue:
          rescue:
        server_chroot:
          hosts:
            chroot:
    vps:
      hosts:
        bastion:
    container:
      children:
        incus_proxy:
          hosts:
            proxy:
        incus_dokuwiki:
          hosts:
            dokuwiki:
        incus_dns:
          hosts:
            dns:
        incus_mail:
          hosts:
            mail:
        incus_sql:
          hosts:
            sql:
        incus_test:
          hosts:
            test:
