---
top_dokuwiki: true

container_hostname: "dokuwiki{{ ip3 | default('') }}"
container_ipv4: "{{ container_ipv4_root }}.{{ param_ip4_dokuwiki }}"
container_ipv6: "{{ container_ipv6_root }}:{{ param_ip4_dokuwiki }}"
